### ISSUE TITLE
Encountered a watt calculation problem after having two loads.

### ISSUE THREAD

**Issue by PanduHalimie31** [RobTillaart/ACS712#14]
Hello, it's me again but with another problem.

I was measuring the device with a single load (22W Fan) and it works just fine, below is the measurements result:
![image](https://user-images.githubusercontent.com/85004246/178666815-fe2e321e-1ff1-4739-9ba9-ecffd5d0b113.png)

Then i measured my second fan (20W Fan) and here's the result:
![image](https://user-images.githubusercontent.com/85004246/178671452-21d83340-7355-4f87-a714-71dc8fcaf1f7.png)

And here's when i used both fan as the loads.
![image](https://user-images.githubusercontent.com/85004246/178671560-f3824173-9f79-4f0c-b601-d20f8915bd61.png)

Wierdly, the image show the watt is not working normally. I used Wattmeter device for comparison and it shows 40Watt but the ACS seems not working normally. Tried with other load too and there goes the same problem again.

Here's the code i used for calculating the Ampere and the Watts
![image](https://user-images.githubusercontent.com/85004246/178672024-4a46cbd5-eb64-4603-a6e9-2b06ac2c6f5d.png)

**Comment by RobTillaart** [comment]
Warning: never post an image of code as those are pretty hard to run on a computer (I cannot test it).

your code is wrong.
Debug it.

**Comment by RobTillaart** [comment]
Oops wrong button.

**Comment by RobTillaart** [comment]
if mA == 218  how can Watt become 17.58 ?
Follow the math you do with paper and pencil

**Comment by PanduHalimie31** [comment]
Yes, there's some miscalculations on the codes.
But i fixed it already with the help of Arduino Forum by using 
`float Watt = ((220L*mA)/1000.0);` instead.

Thanks for answer and time sir!

**Comment by RobTillaart** [comment]
What output do you get now?

The solution of the forum is not 100% optimal.
```cpp
float Watt = mA * (220 / 1000.0);
```
The compiler will optimize the division compile time so in it will in essence be
```cpp
float Watt = mA * 0.22;
```
As multiplications are faster than divisions on most micros, this solution will be slightly faster too.

The forum code will not be optimized and will have both a multiplication and division.
(for most projects the difference is not relevant, but for real time it may just make the difference)

----

Better use the forum for all code problems, there are far more people there to help out.
Only when there are problems in the library code itself you should open an issue under a library.
