### ISSUE TITLE
setADC() cause freeze arduino when i2c device attached

### ISSUE THREAD

**Issue by ikhoeyZX** [RobTillaart/ACS712#48]
when try to using setADC() arduino hung if lcd i2c attached, but when disconnected lcd it run without any issue

**Comment by RobTillaart** [comment]
Thanks for the issue.
Can you provide some info e.g address of i2c lcd and the address of the external adc.
Furthermore a minimal sketch that shows the problem might help me to reconstruct the issue.

**Comment by RobTillaart** [comment]
As no info is provided I assume the problem is solved.
Feel free to reopen the issue if needed (and please provide requested info)
